### ISSUE TITLE
Crash With Version 1.0.2

### ISSUE THREAD

**Issue by Talbe1** [spiralhalo/JpgMcScreenshot#1]
The game crashes upon launch.

Game version: 1.18.2
Modloader: Fabric.

Extra info (log):
[latest.log](https://github.com/spiralhalo/JpgMcScreenshot/files/11573397/latest.log)

**Comment by spiralhalo** [comment]
Should be fixed in https://github.com/spiralhalo/JpgMcScreenshot/commit/dc74a5cb0121132030597c8c3cdc06ef7aae22bc, released as [1.0.3](https://modrinth.com/mod/jpgscreenshot/version/1.0.3)
